version: '3.1'

services:

  db:
    image: rameijeiras/pandorafms-percona-base
    restart: always
    command: ["mysqld", "--innodb-buffer-pool-size=300M"] 
    environment:
      MYSQL_ROOT_PASSWORD: pandora
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: pandora
    networks:
     - pandora

  pandora:
    image: rameijeiras/pandorafms-community
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: pandora
      DBHOST: db
      DBNAME: pandora
      DBUSER: pandora
      DBPASS: pandora
      DBPORT: 3306
      INSTANCE_NAME: pandora01
      SLEEP: 10
      RETRIES: 5
    volumes:
      - mysql:/var/lib/mysql
    networks:
     - pandora
    ports:
      - "8080:80"
      - "41121:41121"
      - "162:162/udp"

networks:
  pandora:
volumes:
  mysql:
